import React from 'react';
import { Box, Typography } from '@mui/material';
import Footer from 'src/components/Footer';

const Affiliates = () => {
  return (
    <Box sx={{ 
      display: 'flex', 
      flexDirection: 'column', 
      minHeight: '100vh', 
    }}>
      <Box sx={{ flex: 1,padding: '20px' }}>
        <Typography variant="h1" gutterBottom>
          Affiliates
        </Typography>
        <Typography variant="body1" paragraph>
          Tradetron is the future of algorithmic trading. An incredibly powerful platform to empower strategy creators by allowing them to automate their quant strategies and sell them to investors and traders the world over. All of this without the hassle of coding. As an affiliate of Tradetron, there is a lot you have to gain.
        </Typography>
        
        <Typography variant="h3" gutterBottom>
          What’s in it for you
        </Typography>
        <Typography variant="body1" paragraph>
          Recurring commissions of 20% on all revenue generated by your referrals.
        </Typography>
        <Typography variant="body1" paragraph>
          Digital marketing assets are available for each program. They already have your affiliate referral tag; so go ahead and share those on social media to get more people to sign up and subscribe.
        </Typography>
        <Typography variant="body1" paragraph>
          Use your affiliate ID to refer to any Tradetron page. Display the link on your site, social media, or emails.
        </Typography>
        <Typography variant="body1" paragraph>
          Commissions can be tracked in real time. As soon as a customer pays, your share of commissions start showing up on your dashboard. Subscription fees, as well as our fees earned via selling of strategies purchased by your referrals, will be considered for your commission calculation.
        </Typography>
        <Typography variant="body1" paragraph>
          For example: A user signs up for Rs.1000 plan. Your commission will be Rs.200 per month. Same user purchases a strategy for Rs.1000. Our fees for this happen to be Rs.200 (20% of what's charged by strategy creator). So your commissions would be Rs.40 per month. In essence, you earn 20% of all what we earn from your referral.
        </Typography>
        <Typography variant="body1" paragraph>
          Commissions will be only on Tradetron subscription and not on any other services provided by Tradetron to the users.
        </Typography>
        <Typography variant="body1" paragraph>
          Payouts over Rs.2000 are settled monthly.
        </Typography>
        <Typography variant="body1" paragraph>
          We provide real-time reporting on your earnings and regular payouts on your account page.
        </Typography>

        <Typography variant="body1" paragraph>
          Read the full Affiliate Terms here.
        </Typography>

        <Typography variant="h3" gutterBottom>
          Sign up for your affiliate account
        </Typography>
        <Typography variant="body1" paragraph>
          Indian Affiliates, click here to sign up.
        </Typography>
        <Typography variant="body1" paragraph>
          USA Affiliates, click here to sign up.
        </Typography>

        <Typography variant="h3" gutterBottom>
          Login here to access your affiliate dashboard
        </Typography>
        
        <Typography variant="body1" paragraph>
          Check this video to see how to become an affiliate.
        </Typography>
      </Box>

      <Footer />
    </Box>
  );
}

export default Affiliates;
